In [1]:
#Create Numpy / n-d arrays
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#Initializing array with zeros and its shape 
arr3 = np.zeros((2,3))
print(arr3)

arr4 = np.ones((3,3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Creating Dialognal matric for the identity matrix 
arr5 = np.identity((5))
arr5 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
# Creating a array list using the arange funtion
arr6 = np.arange(5)
print(arr6)
arr61 = np.arange(5,16)
print(arr61)
#uses step function
arr62 = np.arange(5,16,2)
print(arr62)

[0 1 2 3 4]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 5  7  9 11 13 15]


In [7]:
# linspace function (Linerarly spaced between the lower range and upper range)
arr7 = np.linspace(10,20,10)
arr7 
#output will be btw 10-20 where as there will be 10 equal splits between 10 to 20

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [8]:
#copy function
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

## Numpy Attributes

In [9]:
print(arr1)
arr1.shape

[1 2 3 4 5]


(5,)

In [10]:
# dim function to get the dimention
arr9 = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(arr9)
arr9.shape

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


(2, 2, 2)

In [11]:
arr9.ndim

3

In [12]:
print(arr9.size)
print(arr9.itemsize)
print(arr8.itemsize)

8
4
8


In [13]:
arr9.dtype

dtype('int32')

In [14]:
#Convert the data types
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[4., 5.],
        [6., 7.]]])

## List Vs Array - proving array is faster

In [15]:
# Proving less memory taken by array than list
import sys
lista = range(100)
arr11 = np.arange(100)

In [16]:
sys.getsizeof(80)*len(lista) # getting the size of 80 in the lista

2800

In [17]:
arr11.itemsize*arr11.size

400

In [18]:
# Proving faster retrivel taken by array than list
import time
x = range(1000000)
y = range(1000000,2000000)

start_time = time.time()

z = [x+y for x,y in zip(x,y)]

print('Time taken:', time.time()-start_time)
print(len(z))

Time taken: 0.0989828109741211
1000000


In [19]:
a = np.arange(1000000)
b = np.arange(1000000,2000000)
start_time = time.time()

c = a + b

print('Time taken:', time.time()-start_time)
print(c.size)

Time taken: 0.0019991397857666016
1000000


## Indexing, Slicing and Iteration in NUMPY


In [20]:
# Reshape function to shape the array on given format;
arr12 = np.arange(24).reshape(6,4)
print(arr12)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [21]:
arr1

array([1, 2, 3, 4, 5])

In [22]:
arr1[3]

4

In [23]:
arr1[2:4]

array([3, 4])

In [24]:
arr1[-1]

5

In [25]:
print(arr12)
arr12[2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([ 8,  9, 10, 11])

In [26]:
#to extract 3rd column,
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [27]:
# Extract 9,10,13,14 from array
arr12[2:4,1:3]
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

## Iteration  

In [28]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [30]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## Numpy Array operation 

In [31]:
arr1

array([1, 2, 3, 4, 5])

In [32]:
arrx = np.array([6,7,8,9,10])
arrx

array([ 6,  7,  8,  9, 10])

In [33]:
arr1-arrx

array([-5, -5, -5, -5, -5])

In [34]:
arr1 * arrx # --> Vector multiplication

array([ 6, 14, 24, 36, 50])

In [35]:
arr1*2 # --> Scalar Multiplication

array([ 2,  4,  6,  8, 10])

In [36]:
arrx>3 # --> Checking the array item is greater than 3

array([ True,  True,  True,  True,  True])

In [37]:
arr13 = np.arange(6).reshape(2,3)
arr14 = np.arange(6,12).reshape(3,2)
print(arr13)
print(arr14)

[[0 1 2]
 [3 4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [38]:
#Dot product of array's

arr13.dot(arr14)

array([[ 28,  31],
       [100, 112]])

In [39]:
arr1.dot(arrx)

130

In [40]:
arr1.dot(arr14)

ValueError: shapes (5,) and (3,2) not aligned: 5 (dim 0) != 3 (dim 0)

In [ ]:
# Min and Max function to get the min and max values from Numpy array item
print(arr14)

print("Min Value:", arr14.min())
print("Max value:", arr14.max())

In [ ]:
# find the min or max value and get its row/column from the array using axis=0 {Column wise} and axis=1 {row wise}

print(arr14)
print("Min Value columnwise:", arr14.min(axis=0))
print("Max Value rowwise:", arr14.max(axis=1))
print("Sum Columnwise:",arr14.sum(axis=0))
print("Sum Rowwise:", arr14.sum(axis=1))


In [ ]:
# Basic stats from the array; Mean,Median,STD,
print("Mean values:", arr14.mean())
print("Standard Deviation:", arr14.std())
print("Median", np.median(arr14))
print("Sin Value:", np.sin(arr14))
print("Exponent Value:", np.exp(arr14))

## Reshaping Numpy Arrays

In [ ]:
# Ravel function , brings down higher dimention array to single dimension array just like nditer()
print(arr12)
print("\nDimension:", arr12.ndim)
print("\nReshaping using ravel:", arr12.ravel()) # Brought down to 1d array
print("\nReshaped Dimension:", arr12.ravel().ndim)

In [ ]:
# Reshape function to shape the array on given format;
arr15 = np.arange(24).reshape(4,6)
print(arr15)

In [ ]:
# Transpose function
print(arr14)
print("Transpose:", arr14.transpose())

In [ ]:
# Stacking: combine 2 arrays into single one
arr2x = np.arange(12,18).reshape(2,3)
print("arr2:\n", arr2)
print("arr2x:\n", arr2x)

print("Horizontal stack:\n", np.hstack((arr2,arr2x))) #--> Horizontal Stack
print("Vertical Stack:\n", np.vstack((arr2,arr2x)))

In [ ]:
# Splitting (Horrizontal & Vertical Split)
print(arr2)
print("Hsplit:\n", np.hsplit(arr2,3))
print("Vsplit:\n", np.vsplit(arr2,2))

## Fancy Indexing

In [ ]:
# Lets say wanted to get 1st,4th row.
print(arr12)
print("1st,4th row:\n", arr12[[0,3]])

## Indexing with Boolean Arrays - Filtering Values

In [ ]:
ar = np.random.randint(low=1,high=100,size=24).reshape(4,6)
ar

In [ ]:
ar>50

In [ ]:
# Indexing using boolean arrays; filtering array .
ar[ar>50]

In [ ]:
ar[(ar>50) & (ar%2!=0)] # adding multiple conditions

In [ ]:
# Settingup the value to ZERO on the resultant condition\
ar[(ar>50) & (ar%2!=0)]=0
ar

## Plotting Graphs using numpy

In [ ]:
x = np.linspace(-40,40,100)
x

In [ ]:
y = np.sin(x)
y

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.plot(x,y)

In [ ]:
y = x*x+2*x+6
y

In [ ]:
plt.plot(x,y)

## Broadcasting Numpy

### Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:
#### Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ####ones on its leading (left) side.
#### Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is #### stretched to match the other shape.
#### Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [ ]:
# Scenario 1: Let's look at adding a two-dimensional array to a one-dimensional array
m = np.ones((2, 3))
a = np.arange(3)
print(m.shape)
print(a.shape)
print(m)
print(a)
# Rule1: since the shape of the a array is in lesser dimension 1 will be padded to the shape of array a. a.shape -> (1, 3)


Let's consider an operation on these two arrays. The shape of the arrays are

M.shape = (2, 3)

a.shape = (3,)

We see by rule 1 that the array a has fewer dimensions, so we pad it on the left with ones:

M.shape -> (2, 3)

a.shape -> (1, 3)

By rule 2, we now see that the first dimension disagrees, so we stretch this dimension to match:

M.shape -> (2, 3)

a.shape -> (2, 3)

The shapes match, and we see that the final shape will be (2, 3):

In [ ]:
m+a #Added based on rule1

In [ ]:
# Scenario 2: Let's take a look at an example where both arrays need to be broadcast
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a.shape)
print(b.shape)
print(a)
print(b)

# Rule1: since the shape of the a array is in lesser dimension 1 will be padded to the shape of array a. a.shape -> (3,1) hence broadcasting is possible


### Again, we'll start by writing out the shape of the arrays:

a.shape = (3, 1) 

b.shape = (3,)

Rule 1 says we must pad the shape of b with ones:

a.shape -> (3, 1)

b.shape -> (1, 3)

And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array:

a.shape -> (3, 3)

b.shape -> (3, 3)

Because the result matches, these shapes are compatible. We can see this here:



In [ ]:
a + b

In [ ]:
# Scenario 3: Now let's take a look at an example in which the two arrays are not compatible
M = np.ones((3, 2))
a = np.arange(3)


This is just a slightly different situation than in the first example: the matrix M is transposed. How does this affect the calculation? The shape of the arrays are

M.shape = (3, 2)

a.shape = (3,)

Again, rule 1 tells us that we must pad the shape of a with ones:

M.shape -> (3, 2)

a.shape -> (1, 3)

By rule 2, the first dimension of a is stretched to match that of M:

M.shape -> (3, 2)

a.shape -> (3, 3)

Now we hit rule 3–the final shapes do not match, so these two arrays are incompatible, as we can observe by attempting this operation


In [ ]:
M + a

## Numpy Functions
Seed() function will get the same value again and again.

Uniform() - get a random value betweend the given range. 

randint() - random integer in the range

argmax() - index of the max value in the array

argmin() - index of the min value in the array

where()  - where(condition,true,false)

sort() - sort the array.

percentile() - takes % and array value percentile(a,25)

In [ ]:
np.random.random()

In [ ]:
np.random.seed(1)
np.random.random()

In [ ]:
np.random.uniform(low=1,high=10)

In [ ]:
np.random.uniform(1,10,6).reshape(2,3)

In [ ]:
a = np.random.randint(1,10,15).reshape(3,5)
a

In [ ]:
b = np.random.randint(1,10,6)
b

In [ ]:
b[np.argmax(b)]

In [ ]:
b[np.argmin(b)]

In [ ]:
a = np.random.randint(1,50,6)
a

In [ ]:
# Checking if the value is ODD number and replace the value with -1 
[a%2==1]

In [ ]:
a[a%2==1]=-1
a

In [ ]:
a = np.random.randint(1,50,6)
a

In [ ]:
# creating the new array not replacing the source array.
np.where(a%2==1,-1,a)

In [ ]:
a

In [ ]:
a = np.sort(a)
a

In [ ]:
np.percentile(a,25)

In [ ]:
np.percentile(a,50)

In [ ]:
np.percentile(a,75)